name: Build Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load Config
      id: config
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        CONFIG_FILE="${BRANCH_NAME}_config.env"
        echo "Loading configuration from $CONFIG_FILE"
        source $CONFIG_FILE
        echo "STRIMZI_VERSION=${STRIMZI_VERSION}" >> $GITHUB_ENV
        echo "KAFKA_VERSION=${KAFKA_VERSION}" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> $GITHUB_ENV

    - name: Prepare Dockerfile
      run: |
        sed -i "s/\${STRIMZI_VERSION}/${{ env.STRIMZI_VERSION }}/g" Dockerfile
        sed -i "s/\${KAFKA_VERSION}/${{ env.KAFKA_VERSION }}/g" Dockerfile

    - name: Check plugins.config exists
      run: |
        if [ ! -f plugins.config ]; then
          echo "plugins.config does not exist, skipping plugin download."
          exit 1
        else          
          cat plugins.config
          echo "plugins.config found, proceeding with plugin download."
        fi

    - name: Install Confluent Hub CLI
      run: |
        wget -qO - http://packages.confluent.io/deb/7.6/archive.key | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/7.6 stable main"
        sudo apt-get update && sudo apt-get install confluent-hub-client

    - name: Download Plugins
      run: |
        mkdir -p plugins
        cat plugins.config # Debug: Print the content of plugins.config for verification
        while IFS= read -r plugin || [[ -n "$plugin" ]]; do
          echo "Processing: $plugin"
          if [[ $plugin == http* ]]; then
            echo "Detected URL, attempting to download: $plugin"
            wget -P ./plugins "$plugin" && echo "Download successful: $plugin" || echo "Download failed: $plugin"
          else
            IFS=':' read -r PLUGIN_NAME PLUGIN_VERSION <<< "$plugin"
            if [[ -z "$PLUGIN_NAME" || -z "$PLUGIN_VERSION" ]]; then
              echo "Invalid plugin specification: $plugin"
            else
              echo "Detected plugin, attempting to install: $PLUGIN_NAME:$PLUGIN_VERSION"
              confluent-hub install --no-prompt --component-dir ./plugins $PLUGIN_NAME:$PLUGIN_VERSION && echo "Installation successful: $PLUGIN_NAME:$PLUGIN_VERSION" || echo "Installation failed: $PLUGIN_NAME:$PLUGIN_VERSION"
            fi
          fi
        done < plugins.config


    - name: Build Docker image
      run: docker build . --file Dockerfile --tag "${{ env.DOCKER_IMAGE_NAME }}:${{ env.STRIMZI_VERSION }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push "${{ env.DOCKER_IMAGE_NAME }}:${{ env.STRIMZI_VERSION }}"
      env:
        DOCKER_IMAGE_TAG: ${{ steps.commit_id.outputs.commit_id }}