name: Build Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load Config
      id: config
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        CONFIG_FILE="${BRANCH_NAME}_config.env"
        echo "Loading configuration from $CONFIG_FILE"
        source $CONFIG_FILE
        echo "STRIMZI_VERSION=${STRIMZI_VERSION}" >> $GITHUB_ENV
        echo "KAFKA_VERSION=${KAFKA_VERSION}" >> $GITHUB_ENV        

    - name: Prepare Dockerfile
      run: |
        sed -i "s/\${STRIMZI_VERSION}/${{ env.STRIMZI_VERSION }}/g" Dockerfile
        sed -i "s/\${KAFKA_VERSION}/${{ env.KAFKA_VERSION }}/g" Dockerfile

    - name: Download Plugins
      run: |
        mkdir -p plugins
        while IFS= read -r plugin; do
          echo 123321
          if [[ $plugin == http* ]]; then
            wget -P ./plugins "$plugin"
          else
            PLUGIN_NAME=$(echo $plugin | cut -d':' -f1)
            PLUGIN_VERSION=$(echo $plugin | cut -d':' -f2)
            confluent-hub install --no-prompt --component-dir ./plugins $PLUGIN_NAME:$PLUGIN_VERSION
          fi
        done < plugins.config

    - name: Get commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag "${{ env.DOCKER_IMAGE_NAME }}:${{ env.STRIMZI_VERSION }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push "${{ env.DOCKER_IMAGE_NAME }}:${{ env.STRIMZI_VERSION }}"
      env:
        DOCKER_IMAGE_TAG: ${{ steps.commit_id.outputs.commit_id }}